extends Control

# Define GridContainer and the list of filter titles
#@onready var grid_container = %FilterGrid
@export var FilterObject: PackedScene

#
## List of filters with emojis as titles
#var filter_titles = [
	#"🤓 Engineer",
	#"💼 Executive",
	#"👵 Senior",
	#"🤓 Developer",
	#"💰 Finance",
	#"♾️ Sys Admin",
	#"☕️ JavaScript",
	#"🍑 Backend",
	#"🐀 Golang",
	#"☁️ Cloud",
	#"🚑 Medical",
	#"🎨 Front End",
	#"🥞 Full Stack",
	#"♾️ Ops",
	#"🎨 Design",
	#"⚛️ React",
	#"🔑 InfoSec",
	#"🚥 Marketing",
	#"📱 Mobile",
	#"✍️ Content Writing",
	#"📦 SaaS",
	#"🎯 Recruiter",
	#"⏰ Full Time",
	#"🤖 API",
	#"💼 Sales",
	#"💎 Ruby",
	#"👨‍🏫 Education",
	#"♾️ DevOps",
	#"👩‍🔬 Stats",
	#"🐍 Python",
	#"🔗 Node",
	#"🇬🇧 English",
	#"🔌 Non Tech",
	#"📼 Video",
	#"🎒 Travel",
	#"🔬 Quality Assurance",
	#"🛍 Ecommerce",
	#"👨‍🏫 Teaching",
	#"🐧 Linux",
	#"☕️ Java",
	#"🏅 Crypto",
	#"👶 Junior",
	#"📦 Git",
	#"👩‍⚖️ Legal",
	#"🤖 Android",
	#"💼 Accounting",
	#"♾️ Admin",
	#"🖼 Microsoft",
	#"📗 Excel",
	#"🐘 PHP",
	#"☁️ Amazon",
	#"☁️ Serverless",
	#"🎨 CSS",
	#"🤓 Software",
	#"🤔 Analyst",
	#"🅰️ Angular",
	#"🍏 iOS",
	#"🎧 Customer Support",
	#"🔡 HTML",
	#"☁️ Salesforce",
	#"🚥 Ads",
	#"📦 Product Designer",
	#"👋 HR",
	#"🐬 SQL",
	#"🔷 C",
	#"🤓 Web Developer",
	#"🚫 NoSQL",
	#"🐬 Postgres",
	#"➕ C Plus Plus",
	#"⏰ Part Time",
	#"🔷 Jira",
	#"#️⃣ C Sharp",
	#"🔎 SEO",
	#"🚁 Apache",
	#"👩‍🔬 Data Science",
	#"🎧 Virtual Assistant",
	#"⚛️ React Native",
	#"🍃 Mongo",
	#"🧪 Testing",
	#"📦 Architecture",
	#"🔷 Director",
	#"🎵 Music",
	#"🛍 Shopify",
	#"✍️ Wordpress",
	#"🧩 Elasticsearch",
	#"⛓ Blockchain",
	#"💎 Web3",
	#"💧 Drupal",
	#"🐳 Docker",
	#"⚛️ GraphQL",
	#"💼 Payroll",
	#"👩‍🎓 Internship",
	#"🤖 Machine Learning",
	#"📦 Architect",
	#"☕️ Scala",
	#"🎨 Web",
	#"🍏 Objective C",
	#"✍️ Social Media",
	#"💚 Vue",
#]
#
#
#func _ready():
	## Set number of columns for the GridContainer
	#self.columns = 3
	#
	## Create filter objects and add to the grid
	#for title in filter_titles:
		## Instantiate the custom FilterObject
		#var filter_obj = FilterObject.instantiate()
		#filter_obj.setdata(title) # Set the title for the filter
		#add_child(filter_obj)
